# Human Tasks:
# 1. Verify MongoDB connection string format and credentials in secrets
# 2. Configure network policies for service-to-service communication
# 3. Validate Google Maps API key configuration
# 4. Review geographic boundary configurations for North American coverage
# 5. Verify resource quotas align with cluster capacity
# 6. Set up monitoring and alerting for service metrics
# 7. Configure distributed tracing for service requests

---
# Requirement: Location-based Discovery (1.2 System Overview/High-Level Description)
# Deployment configuration for location-based furniture discovery service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: location-service
  namespace: founditure
  labels:
    app: founditure
    component: location-service
spec:
  # Requirement: High Availability (2.1 High-Level Architecture)
  # Minimum 3 replicas for high availability and fault tolerance
  replicas: 3
  selector:
    matchLabels:
      app: founditure
      component: location-service
  template:
    metadata:
      labels:
        app: founditure
        component: location-service
    spec:
      containers:
      - name: location-service
        # Location service container image
        image: founditure/location-service:latest
        ports:
        - containerPort: 3004
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "3004"
        - name: HOST
          value: "0.0.0.0"
        # Import configuration from ConfigMap and Secrets
        envFrom:
        - configMapRef:
            name: founditure-config
        - secretRef:
            name: founditure-secrets
        # Requirement: Scalability (2.2.1 Core Components)
        # Resource limits for container scaling
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "200m"
            memory: "256Mi"
        # Health monitoring configuration
        livenessProbe:
          httpGet:
            path: /health
            port: 3004
          initialDelaySeconds: 30
          periodSeconds: 60
        readinessProbe:
          httpGet:
            path: /health
            port: 3004
          initialDelaySeconds: 15
          periodSeconds: 30

---
# Requirement: Geographic Coverage (1.3 Scope/Implementation Boundaries)
# Service configuration for location-based discovery in North America
apiVersion: v1
kind: Service
metadata:
  name: location-service
  namespace: founditure
  labels:
    app: founditure
    component: location-service
spec:
  selector:
    app: founditure
    component: location-service
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3004
  type: ClusterIP

---
# Requirement: Scalability (2.2.1 Core Components)
# Horizontal Pod Autoscaler for dynamic scaling based on CPU utilization
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: location-service-hpa
  namespace: founditure
  labels:
    app: founditure
    component: location-service
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: location-service
  # Requirement: High Availability (2.1 High-Level Architecture)
  # Scaling configuration with minimum 3 replicas
  minReplicas: 3
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70