# Human Tasks:
# 1. Generate and securely store base64-encoded values for all secret variables
# 2. Configure AWS KMS for encryption key management
# 3. Set up HashiCorp Vault integration for dynamic secret injection
# 4. Configure RBAC policies for service account access
# 5. Enable audit logging for secret access monitoring
# 6. Implement automated key rotation policy
# 7. Verify ISO 27001 compliance requirements are met

# Kubernetes API version v1 for Secrets resource
# Requirement: Data Security (5.2.1 Encryption Standards)
# - Implements AES-256 encryption for data at rest
# - Integrates with AWS KMS for key management
apiVersion: v1
kind: Secret
metadata:
  name: founditure-secrets
  namespace: default
  labels:
    app: founditure
    environment: $(ENVIRONMENT)
    managed-by: terraform
    encryption: aes-256
  annotations:
    # Requirement: Authentication Security (5.1.1 Authentication Methods)
    # - Configures service account for secure access
    kubernetes.io/service-account.name: founditure-sa
    # HashiCorp Vault integration for dynamic secret management
    vault.hashicorp.com/agent-inject: "true"
    vault.hashicorp.com/role: "founditure-role"
type: Opaque
data:
  # Requirement: Database Security (2.2.2 Data Storage Solutions)
  # PostgreSQL credentials
  POSTGRES_USER: $(POSTGRES_USER_B64)
  POSTGRES_PASSWORD: $(POSTGRES_PASSWORD_B64)
  POSTGRES_HOST: $(POSTGRES_HOST_B64)
  
  # MongoDB connection string
  MONGODB_URI: $(MONGODB_URI_B64)
  
  # Redis credentials
  REDIS_PASSWORD: $(REDIS_PASSWORD_B64)
  
  # Requirement: Authentication Security (5.1.1 Authentication Methods)
  # JWT authentication secrets
  JWT_SECRET: $(JWT_SECRET_B64)
  JWT_REFRESH_SECRET: $(JWT_REFRESH_SECRET_B64)
  
  # OAuth provider credentials
  GOOGLE_OAUTH_CLIENT_ID: $(GOOGLE_OAUTH_CLIENT_ID_B64)
  GOOGLE_OAUTH_CLIENT_SECRET: $(GOOGLE_OAUTH_CLIENT_SECRET_B64)
  APPLE_OAUTH_CLIENT_ID: $(APPLE_OAUTH_CLIENT_ID_B64)
  APPLE_OAUTH_CLIENT_SECRET: $(APPLE_OAUTH_CLIENT_SECRET_B64)
  FACEBOOK_OAUTH_CLIENT_ID: $(FACEBOOK_OAUTH_CLIENT_ID_B64)
  FACEBOOK_OAUTH_CLIENT_SECRET: $(FACEBOOK_OAUTH_CLIENT_SECRET_B64)
  
  # Requirement: Cloud Security (5.3.3 Security Compliance/Cloud Security)
  # AWS credentials and configuration
  AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID_B64)
  AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY_B64)
  AWS_REGION: $(AWS_REGION_B64)
  S3_BUCKET_NAME: $(S3_BUCKET_NAME_B64)
  
  # Firebase service account for push notifications
  FIREBASE_SERVICE_ACCOUNT: $(FIREBASE_SERVICE_ACCOUNT_B64)
  
  # Requirement: Data Security (5.2.1 Encryption Standards)
  # AES-256 encryption key for data protection
  AES_ENCRYPTION_KEY: $(AES_ENCRYPTION_KEY_B64)
  
  # External service API keys
  MAPS_API_KEY: $(MAPS_API_KEY_B64)