platform :ios, '14.0'

use_frameworks!
inhibit_all_warnings!

target 'Founditure' do
  pod 'Firebase/Auth', '10.0.0'
  pod 'Firebase/Messaging', '10.0.0'
  pod 'Firebase/Analytics', '10.0.0'
  pod 'Alamofire', '5.8.0'
  pod 'SDWebImage', '5.18.0'
  pod 'GoogleMLKit/ObjectDetection', '4.0.0'
  pod 'Socket.IO-Client-Swift', '16.1.0'
  pod 'GoogleMaps', '8.0.0'
  pod 'Sentry', '8.0.0'
  pod 'SwiftLint', '0.52.0'
  pod 'KeychainAccess', '4.2.2'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.0'
      config.build_settings['ENABLE_BITCODE'] = 'NO'
      config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
      config.build_settings['SWIFT_VERSION'] = '5.9'
      config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'arm64'
      config.build_settings['ONLY_ACTIVE_ARCH'] = 'YES'
      config.build_settings['DEAD_CODE_STRIPPING'] = 'YES'
      config.build_settings['CLANG_WARN_DOCUMENTATION_COMMENTS'] = 'NO'
      config.build_settings['SWIFT_SUPPRESS_WARNINGS'] = 'YES'
      config.build_settings['GCC_WARN_INHIBIT_ALL_WARNINGS'] = 'YES'
    end
  end
end