# Human Tasks:
# 1. Verify MinIO credentials are properly configured in environment variables
# 2. Ensure network connectivity between Tempo and MinIO
# 3. Validate network access between Tempo and Prometheus for metrics forwarding
# 4. Confirm all service endpoints can reach Tempo's receiver ports
# 5. Review retention period and adjust based on storage capacity

# Grafana Tempo version: 2.1.0
# MinIO version: latest

# Server configuration
# Addresses requirement: System Monitoring - Distributed tracing implementation
server:
  http_listen_port: 3200
  grpc_listen_port: 9095
  http_path: /tempo

# Distributor configuration for trace data ingestion
# Addresses requirement: Performance Monitoring - Real-time tracing and monitoring
distributor:
  receivers:
    jaeger:
      protocols:
        grpc:
          endpoint: "0.0.0.0:14250"
        thrift_http:
          endpoint: "0.0.0.0:14268"
    otlp:
      protocols:
        grpc:
          endpoint: "0.0.0.0:4317"
        http:
          endpoint: "0.0.0.0:4318"

# Storage configuration using MinIO
# Addresses requirement: Production Monitoring - 24/7 production monitoring with full tracing
storage:
  trace:
    backend: s3
    s3:
      bucket: tempo-traces
      endpoint: minio:9000
      access_key: ${MINIO_ACCESS_KEY}
      secret_key: ${MINIO_SECRET_KEY}
      insecure: true
    pool:
      queue_depth: 2000
      max_workers: 50
    retention: 336h  # 14 days retention

# Ingestion rate limiting
overrides:
  ingestion_rate_limit: 100000
  ingestion_burst_size: 150000
  max_traces_per_user: 1000000
  max_global_traces_per_user: 1000000

# Search capabilities
search_enabled: true

# Metrics generation configuration
# Addresses requirement: System Monitoring - Comprehensive system observability
metrics_generator:
  registry:
    external_labels:
      source: tempo
      cluster: founditure-prod
  storage:
    path: /tmp/tempo/generator/wal
    remote_write:
      enabled: true
      endpoints:
        - http://prometheus:9090/api/v1/write

# Query configuration
querier:
  frontend_worker:
    frontend_address: "tempo:9095"

# Compactor settings for trace block optimization
compactor:
  compaction:
    block_retention: 336h
    compacted_block_retention: 336h

# Ingester configuration for trace data processing
ingester:
  max_block_duration: 5m
  max_block_bytes: 1073741824  # 1GiB
  trace_idle_period: 10s

# Component lifecycle settings
memberlist:
  abort_if_cluster_join_fails: false
  join_members:
    - tempo

# Usage reporting
usage_report:
  reporting_enabled: false

# Limits configuration
limits:
  max_bytes_per_trace: 50000000  # 50MB
  max_search_bytes_per_trace: 10000000  # 10MB
  max_bytes_per_tag_values_query: 5242880  # 5MB